# Generated by Django 4.1.3 on 2022-12-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0005_data_news_migration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courses",
            options={"verbose_name": "Course", "verbose_name_plural": "Courses"},
        ),
        migrations.AlterModelOptions(
            name="courseteachers",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ("course", "num"),
                "verbose_name": "Lesson",
                "verbose_name_plural": "Lessons",
            },
        ),
    ]
