# Generated by Django 4.1.3 on 2022-12-10 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0006_alter_courses_options_alter_courseteachers_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created",),
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
    ]
